# Generated by Django 2.2.10 on 2022-01-15 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='anonim', max_length=50)),
                ('user_id', models.IntegerField()),
                ('text', models.TextField(max_length=1000)),
                ('answer_multi_1', models.CharField(blank=True, default='answer_1', max_length=200)),
                ('answer_multi_2', models.CharField(blank=True, default='answer_2', max_length=200)),
                ('answer_multi_3', models.CharField(blank=True, default='answer_3', max_length=200)),
                ('answer_multi_4', models.CharField(blank=True, default='answer_4', max_length=200)),
                ('answer_text', models.TextField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_created=datetime.date(2022, 1, 15))),
                ('name', models.CharField(max_length=200)),
                ('finished_date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('style', models.IntegerField(blank=True, default=1)),
                ('answer_multi_1', models.CharField(blank=True, default='answer_1', max_length=200)),
                ('answer_multi_2', models.CharField(blank=True, default='answer_2', max_length=200)),
                ('answer_multi_3', models.CharField(blank=True, default='answer_3', max_length=200)),
                ('answer_multi_4', models.CharField(blank=True, default='answer_4', max_length=200)),
                ('answer_text', models.TextField(blank=True, default='', max_length=2000)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend_polling.Polling')),
            ],
        ),
    ]
