# Generated by Django 2.2.10 on 2022-01-15 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_polling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='start_date',
            field=models.DateField(auto_created=datetime.date(2022, 1, 16)),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, default='answer_text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
