# Generated by Django 2.2.10 on 2022-01-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_polling', '0002_auto_20220116_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_multi_1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_multi_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_multi_3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_multi_4',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
