# Generated by Django 2.2.10 on 2022-01-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_polling', '0003_auto_20220116_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
