# Generated by Django 2.2.10 on 2022-01-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_polling', '0005_auto_20220116_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pol', to='backend_polling.Polling', to_field='number'),
        ),
    ]
