# Generated by Django 2.2.10 on 2022-01-16 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_polling', '0006_auto_20220116_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 16)),
        ),
        migrations.AddField(
            model_name='participant',
            name='polling',
            field=models.CharField(default='', max_length=200),
        ),
    ]
