# Generated by Django 2.2.10 on 2022-01-16 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_polling', '0007_auto_20220116_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 1, 17)),
        ),
        migrations.AlterField(
            model_name='polling',
            name='start_date',
            field=models.DateField(auto_created=datetime.date(2022, 1, 17)),
        ),
    ]
