# Generated by Django 2.2.10 on 2022-01-16 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_polling', '0010_auto_20220117_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
