# Generated by Django 2.2.10 on 2022-01-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_polling', '0012_remove_participant_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='backend_polling.UserCustom'),
        ),
    ]
